### ISSUE TITLE
Typo в pr template?

### ISSUE THREAD

**Issue by cofob** [fire-squad/autodonate#44]
Что значит [эта строчка?](https://github.com/fire-squad/autodonate/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L11) Как её понимать?

**Comment by cofob** [comment]
> Что ты запустил `make test` и больше ничего не меняв, закомитил.

Сложная и непонятная формулировка. Может лучше будет "Изменения успешно проходят тесты `make test`"?

**Comment by PerchunPak** [comment]
Все же понятно написано, не понимаю тебя. Смысл в том что даже из за маленького изменения все может пойти наперекосяк, у меня не раз такое бывало и все из за того что я перед комитом не запустил тесты.

**Comment by cofob** [comment]
> Все же понятно написано, не понимаю тебя. Смысл в том что даже из за маленького изменения все может пойти наперекосяк, у меня не раз такое бывало и все из за того что я перед комитом не запустил тесты.

В том и проблема что не понятно.

**Comment by PerchunPak** [comment]
Разложи предложение на 2 части `Я запустил make test` и `с тех пор ничего не менял.`. Думаю тут очевидно что означает. Давай в ГС дальше обсудим, напиши днем в ТГ.

**Comment by cofob** [comment]
> Разложи предложение на 2 части `Я запустил make test` и `с тех пор ничего не менял.`. Думаю тут очевидно что означает. Давай в ГС дальше обсудим, напиши днем в ТГ.

Я поэтому и открыл что это НЕ очевидно. Сложная и непонятная формулировка.
